name: Aleem Rehman, Web Developer & Mentor
description: Web Developer & Mentor
markdown: kramdown
highlighter: rouge # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: pretty

website: http://aleemrehman.co

author: Aleem Rehman

logo: /images/dist/android-chrome-384x384.png

# Social
social:
  name: Aleem Rehman
  links:
    - https://twitter.com/drmanhttn
    - https://github.com/AleemRehman
  twitter:
    username: drmanhttn
    url: https://twitter.com/
  github:
    username: AleemRehman
    url: https://github.com/
  instagram:
    username: manhttn
    url: https://instagram.com/
  email: contact@aleemrehman.co


#directores
imageurl: /images/dist/
videourl: /videos/

# Global classes
link_classes: link underline-hover blue hover-blue active-black
code_classes: bg-washed-blue pa1
post_heading_classes: f3 lh-title
paragraph_classes: f6 f5-ns

# Gems
gems:
  - jekyll-archives
  - jekyll-feed
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-seo-tag

# Settings for archives
jekyll-archives:
  enabled:
    - categories
  layouts:
    category: 'category-archive'
  permalinks:
    category: '/category/:name/'
  category_archive:
    type: liquid

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/

# Navigation
navigation:
  - title: Projects
    url: /projects/
  - title: Blog
    url: /blog/
  - title: Hire me
    url: /hire-me/
